// auto generated by configure
#ifndef SRS_AUTO_HEADER_HPP
#define SRS_AUTO_HEADER_HPP

#define SRS_AUTO_BUILD_TS "1440054346"
#define SRS_AUTO_BUILD_DATE "2015-08-20 15:05:46"
#define SRS_AUTO_UNAME "Darwin winlin.lan 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64"
#define SRS_AUTO_USER_CONFIGURE "--x86-x64  --export-librtmp-single=/Users/winlin/git/srs.librtmp/src/srs"
#define SRS_AUTO_CONFIGURE "--prefix=/usr/local/srs --without-hls --without-hds --without-dvr --without-nginx --without-ssl --without-ffmpeg --without-transcode --without-ingest --without-stat --without-http-callback --without-http-server --without-stream-caster --without-http-api --with-librtmp --with-research --without-utest --without-gperf --without-gmc --without-gmp --without-gcp --without-gprof --without-arm-ubuntu12 --without-mips-ubuntu12 --log-trace"

#define SRS_X86_X64

#define SRS_AUTO_EMBEDED_TOOL_CHAIN "normal x86/x64 gcc"

#undef SRS_AUTO_HTTP_CORE
#undef SRS_AUTO_HTTP_SERVER
#undef SRS_AUTO_STREAM_CASTER
#undef SRS_AUTO_HTTP_API
#undef SRS_AUTO_NGINX
#undef SRS_AUTO_DVR
#undef SRS_AUTO_HLS
#undef SRS_AUTO_HDS
#undef SRS_AUTO_HTTP_CALLBACK
#undef SRS_AUTO_SSL
#undef SRS_AUTO_MEM_WATCH
#undef SRS_AUTO_FFMPEG_TOOL
#define SRS_AUTO_FFMPEG_STUB
#undef SRS_AUTO_TRANSCODE
#undef SRS_AUTO_INGEST
#undef SRS_AUTO_STAT
#undef SRS_AUTO_GPERF
#undef SRS_AUTO_GPERF_MC
#undef SRS_AUTO_GPERF_MP
#undef SRS_AUTO_GPERF_CP
#undef SRS_AUTO_EMBEDED_CPU
#undef SRS_AUTO_ARM_UBUNTU12
#undef SRS_AUTO_MIPS_UBUNTU12

#undef SRS_AUTO_VERBOSE
#undef SRS_AUTO_INFO
#define SRS_AUTO_TRACE

#define SRS_AUTO_PREFIX "/usr/local/srs"

#define SRS_AUTO_CONSTRIBUTORS "\
winlin<winlin@vip.126.com> \
wenjie.zhao<740936897@qq.com> \
xiangcheng.liu<liuxc0116@foxmail.com> \
naijia.liu<youngcow@youngcow.net> \
alcoholyi<alcoholyi@qq.com> \
byteman<wangchen2011@gmail.com> \
chad.wang<chad.wang.cn@gmail.com> \
suhetao<suhetao@gmail.com> \
Johnny<fengjihu@163.com> \
karthikeyan<keyanmca@gmail.com> \
StevenLiu<lq@chinaffmpeg.org> \
zhengfl<zhengfl_1989@126.com> \
tufang14<breadbean1449@gmail.com> \
allspace<allspace@gmail.com> \
niesongsong<nie950@gmail.com> \
rudeb0t<nimrod@themanxgroup.tw> \
"

#endif
